name: Deploy via SSH to cPanel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # adjust as needed

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🛠 Build React app
        run: npm run build

      - name: 🚀 Deploy via SSH and rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
          CPANEL_USERNAME: ${{ secrets.CPANEL_USERNAME }}
          CPANEL_PORT: ${{ secrets.CPANEL_PORT }}
          CPANEL_DEST_DIR: ${{ secrets.CPANEL_DEST_DIR }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Optional: disable host key checking for smooth CI (not recommended for super-secure envs)
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

          rsync -avz -e "ssh -p $CPANEL_PORT" --delete dist/ $CPANEL_USERNAME@$CPANEL_HOST:$CPANEL_DEST_DIR
